version: "3.3"
services:
  app:
    container_name: "contenedor-app"
    build:
      context: .
      tags:
        - "app:1.0.0"
    ports:
      - "8080:8080"
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=50m
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: "0.3"
        reservations:
          memory: 100M
          cpus: "0.1"
