name: Build Docker Image

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      app_tag:
        description: "Name of tag"
        required: true
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.4.0
        id: versionId
        with:
          major_pattern: "major"
          minor_pattern: "feat:"
          tag_prefix: "tag"
          version_format: "${tag}"
        #   version_format: "${major}.${minor}.${patch}-prerelease${increment}"

      - name: Build Docker Image.
        env:
          IMAGE_NAME: "astro-app"
          NEW_VERSION: ${{steps.versionId.outputs.version}}
        run: docker build --tag ${IMAGE_NAME}:${NEW_VERSION} .
