name: Build Docker Image

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      app_tag:
        description: "Name of tag"
        required: true
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image.
        env:
          IMAGE_NAME: "astro-app"
          TAG: ${{ github.event.inputs.app_tag || github.ref_name }}
        run: docker build --tag ${IMAGE_NAME}:${TAG} .
